server:
  port: 9002
spring:
  application:
    name: consent-manager

  datasource:
    url: jdbc:mysql://localhost:3306/ehrc
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update