server:
  port: 9002
spring:
  application:
    name: hospital-service

  datasource:
    url: jdbc:mysql://localhost:3306/hospitaldb1
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update